version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: "no"
    volumes:
      - '${NGINX_DATA_DIR:?}/config/certs:/etc/nginx/certs'
      - '${NGINX_DATA_DIR}/config/nginx.conf:/etc/nginx/nginx.conf'
      - '${NGINX_DATA_DIR}/config/conf.d:/etc/nginx/conf.d'
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: ${NETWORK}
