version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: "no"
    volumes:
      - '${NGINX_HOST_DATA_DIR:?}/config/certs:/etc/nginx/certs'
      - '${NGINX_HOST_DATA_DIR}/config/nginx.conf:/etc/nginx/nginx.conf'
      - '${NGINX_HOST_DATA_DIR}/config/conf.d:/etc/nginx/conf.d'
      # used by tlrl.gnoht.com.conf, just need it to be readable
      - '${ARCHIVE_HOST_DATA_DIR:?}:/data/archive'
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: ${NETWORK}
