version: '3.7'

# Make the default network the upstream/external network given to us.
networks:
  default:
    external:
      name: ${NETWORK:?}

services:
  postgres:
    image: postgres:12.3-alpine
    container_name: postgres
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - TLRL_DB_NAME=${TLRL_DB_NAME:?}
      - TLRL_DB_ADMIN=${TLRL_DB_ADMIN:?}
      - TLRL_DB_ADMIN_PASSWORD=${TLRL_DB_ADMIN_PASSWORD:?}
      - TLRL_DB_USER=${TLRL_DB_USER:?}
      - TLRL_DB_USER_PASSWORD=${TLRL_DB_USER_PASSWORD:?}
    volumes:
      - "${POSTGRES_HOST_DATA_DIR:?}/pgdata:/var/lib/postgresql/data"
      - "${POSTGRES_HOST_DATA_DIR}/scripts:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
