version: '3.7'

# Make the default network the upstream/external network given to us.
networks:
  default:
    external:
      name: ${NETWORK:?}

services:
  postgres:
    image: postgres:12.3-alpine
    container_name: postgres
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - "${POSTGRES_DATA_VOLUME:-/data/postgres}:/var/lib/postgresql/data"
      - "./scripts:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_SERVER_PORT:-5432}:5432"
