version: '3.7'

# Make the default network the upstream/external network given to us.
networks:
  default:
    external:
      name: ${NETWORK:?}

services: 
  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - '${ZK_DATA_DIR}:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=${ZK_ALLOW_ANONYMOUS_LOGIN:-no}
